apiVersion: v1
kind: Config
clusters:
- name: ${name}
  cluster:
    certificate-authority: certs/ca.crt
    server: https://${api}
users:
- name: ${user}
  user:
    client-certificate: certs/${cert_name}.crt
    client-key: certs/${cert_name}.key
contexts:
- context:
    cluster: localcluster
    user: ${user}
  name: ${name}
current-context: ${name}
