apiVersion: v1
kind: Config
clusters:
- name: ${name}
  cluster:
    insecure-skip-tls-verify: true
    server: http://localhost:8080
users:
- name: ${user}
contexts:
- context:
    cluster: ${name}
    user: ${user}
  name: ${name}
current-context: ${name}
