apiVersion: v1
kind: Pod
metadata:
  name: squid
  namespace: "kube-system"
  labels:
    component: squid-proxy
spec:
  hostNetwork: true
  containers:
  - name: squid
    image: ${squid_image}
    ports:
    - containerPort: 3128
      hostPort: 3128
      name: https
    volumeMounts:
      - name: "whitelist"
        mountPath: "/authorized_sites"
  volumes:
    - name: "whitelist"
      hostPath:
        path: "/etc/squid"
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: kube-system
spec:
  ports:
  - port: 3128
    protocol: TCP
    targetPort: 3128
  selector:
    component: squid-proxy
  sessionAffinity: None
  type: ClusterIP

