apiVersion: "v1"
kind: "Pod"
metadata:
  name: "kube-scheduler"
  namespace: "kube-system"
  labels:
    tier: control-plane
    component: kube-scheduler
spec:
  hostNetwork: true
  containers:
    - name: "kube-scheduler"
      image: "${hyperkube}"
      command:
        - "/hyperkube"
        - "scheduler"
        - "--master=127.0.0.1:8080"
        - "--kubeconfig=/etc/kubernetes/kubeconfig.yaml"
        - "--v=1"
      volumeMounts:
        - name: "etc-kubernetes"
          mountPath: "/etc/kubernetes"
        - name: "var-lib-kubelet"
          mountPath: "/var/lib/kubelet"
  volumes:
    - name: "etc-kubernetes"
      hostPath:
        path: "/etc/kubernetes"
    - name: "var-lib-kubelet"
      hostPath:
        path: "/var/lib/kubelet"
